// console.log('our bangladesh')
// console.log('my name is limon')

// try{
    
//     console.log(district)
//     const district = "bBaria"

// }catch(error){
//     // console.log("inside from catch block")
//     // console.log(error)
//     console.error("this is the error message")
// }

// console.log("dekhi cole kina")


/**
 * this err object has two property
 * 1: name -> give the error name
 * 2: message -> give the full details about this error
 */

try{
    addlert("gives error")
}catch(err){
    console.log(err.name)
}


